on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.TBL03_SECRET }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.subId }}
        resourceGroupName: ${{ vars.TBL03_VARIABLE }}
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webAppName=${{ vars.TARGETENV }}

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}