on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this is job 1"
          echo "this is second line in job 1"
      
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job 2"
      - name: Cowsays
        # You may pin to the exact commit or the version.
        # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
        uses: mscoutermarsh/cowsays-action@v1
        with:
          # What does the cow say?
          text: # optional, default is Ship it!!!!!
          # Color of your cow
          color: # optional, default is white

